language: go

go:
  - 1.8.x

before_install:
 - mkdir -p $GOPATH/bin
 - sudo add-apt-repository -y ppa:masterminds/glide
 - sudo apt-get update
 - sudo apt-get -y install glide

install:
 - glide install
 - go vet
 - go build

script: echo 1
