version: '2'
services:
  api:
    build: .
    ports:
     - 8080:8080
    links:
     - postgres

  postgres:
    image: postgres:alpine
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=blooper
     - POSTGRES_DB=blooper
     - POSTGRES_PASSWORD=ZThnie2mffo2cEAA5E2bytnKW3IgA9vZ
    volumes:
     - ./postgresql:/var/lib/postgresql/data
