version: '2'
services:
  api:
    build: .
    ports:
     - 8080:8080
    links:
     - cassandra

  cassandra:
    image: cassandra
    ports:
     - 9042:9042
    volumes:
     - ./cassandra:/var/lib/cassandra
