version: '2'
services:
  api:
    build: .
    ports:
     - 8080:8080
    links:
     - postgres
    env_file:
     - docker.env

  postgres:
    image: postgres:alpine
    ports:
     - 5432:5432
    env_file:
     - docker.env
    volumes:
     - ./postgresql:/var/lib/postgresql/data
