#%RAML 1.0

title: Revision API

post:
  securedBy: [BLOOPER-TOKEN]
  description: Post a revision

/{revision}:
  get:
    description: Get a specific revision
  put:
    securedBy: [BLOOPER-TOKEN]
    description: Update a specific revision
  delete:
    securedBy: [BLOOPER-TOKEN]
    description: Delete a specific revision

  /comments:
    get:
      description: Get comments of a specific revision