#%RAML 1.0

title: User API

/signin:
  post:
    description: Sign in as user

/self:
  get:
    securedBy: [BLOOPER-TOKEN]
    description: Get authenticated user
  put:
    securedBy: [BLOOPER-TOKEN]
    description: Update authenticated user

  /blueprints:
    get:
      securedBy: [BLOOPER-TOKEN]
      description: Get authenticated user blueprints

/{user}:
  get:
    description: Get specific user

  /blueprints:
    get:
      description: Get specific user blueprints