#%RAML 1.0

title: Comment API

post:
  description: Post a new comment

/{comment}:
  get:
    description: Get a specific comment
  put:
    description: Update a specific comment
  delete:
    description: Delete a specific comment