#%RAML 1.0 SecurityScheme

type: Pass Through
description: Require a header for authentication
displayName: Blooper Access Token (BLOOPER-TOKEN)

describedBy:
  headers:
    BLOOPER-TOKEN:
      type: string

settings:
  signatures: PLAINTEXT