#%RAML 1.0

title: Blooper
version: v1

mediaType: application/json

securitySchemes:
  BLOOPER-TOKEN: !include security/blooper-token.raml

/tags: !include tag/tags.raml
/comment: !include comment/comment.raml
/blueprint: !include blueprint/blueprint.raml
/blueprints: !include blueprint/blueprints.raml
/user: !include user/user.raml
/revision: !include revision/revision.raml