swagger: '2.0'

consumes:
  - application/json

produces:
  - application/json

definitions: {}

info:
  $ref: ./info.yaml

host: blooper-api.vil.so

tags:
- name: Blueprint
- name: Comment
- name: Revision
- name: Tag
- name: User

schemes:
- https

securityDefinitions:
  BLOOPER-TOKEN:
    type: apiKey
    name: BLOOPER-TOKEN
    in: header

basePath: "/v1"

paths:
  $ref: ./paths.yaml

definitions:
  $ref: ./definitions.yaml